version: '3.4'
services:
  tunneling:
    image: ghcr.io/t7tran/ssh-tunneling:1.3.0
    read_only: true
    ports:
    - 2222:2222
    volumes:
    - home:/home:rw
    - temp:/tmp:rw
    - ./opt:/opt:ro
  custom-tunneling:
    image: ghcr.io/t7tran/ssh-tunneling:1.3.0
    read_only: true
    command:
    - /usr/sbin/sshd
    - -D
    - -f
    - /etc/whitelist_sshd_config
    - -e
    ports:
    - 2223:2222
    volumes:
    - ./whitelist_sshd_config:/etc/whitelist_sshd_config:ro
    - home:/home:rw
    - temp:/tmp:rw
    - ./opt:/opt:ro
volumes:
  home:
    labels:
    - "app=sshtunneling"
  temp:
    labels:
    - "app=sshtunneling"
